### PR TITLE
remove thoth-sourcemanagement from dependencies

### PR DESCRIPTION
**Pull request by KPostOffice**
## Description

thoth-sourcemanagement isn't used anywhere

### CODE REVIEW

**Comment by pacospace** [comment]
> ## Description
> thoth-sourcemanagement isn't used anywhere

Kebechet should tell us that :) maybe a new feature? @KPostOffice

**Comment by KPostOffice** [comment]
> > ## Description
> > thoth-sourcemanagement isn't used anywhere
> 
> Kebechet should tell us that :) maybe a new feature? @KPostOffice

https://github.com/thoth-station/kebechet/issues/727

**Review by harshad16 — COMMENTED** [review]
/lgtm
thanks

**Review by pacospace — APPROVED** [review]
Thanks!!

**Pull request merged**
